
export const appFood = [
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/NPYkEhI-YPzICgh-cPRFsBA.jpeg',
        title: 'Salmon Snack Set',
        category: 'starters',
        price: 298,
        id: 1,
        description: 'Odesa style forshmak, perfectly salted salmon, hummus with olive oil and nuts, guacamole of perfect avocado, 420 g',
    },
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/PbmbjbB-bGKDdCb-RDkDqVT_GwH.jpeg',
        title: 'Camembert baked with caramelized quince and viburnum coulis',
        category: 'starters',
        price: 198,
        id: 2,
        description: '250 g',
    },
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/lnMGUH-teDJlND-GRUUDHe.jpeg',
        title: 'The most delicate chicken liver pate with brioche and caramelized cnion jam',
        category: 'starters',
        price: 99,
        id: 3,
        description: '150 g',
    },
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/Xaaadhc-uuIlxQF-mFcfycH_iF.jpeg',
        title: 'Hummus with avocado mousse, tomatoes, aromatic herbs and chia',
        category: 'starters',
        price: 149,
        id: 4,
        description: '140 g',
    },
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/gIHmxHL-qSjHVsa-CPUyGFp_ilI.jpeg',
        title: 'Guacamole with soft egg, fresh cilantro, spicy chili and warm baguette',
        category: 'starters',
        price: 169,
        id: 5,
        description: '230 g',
    },
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/jeWWJFe-JkBSFIW-SeAHeQt_OHD.jpeg',
        title: 'Spicy beef tartare',
        category: 'starters',
        price: 229,
        id: 6,
        description: '240 g',
    },
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/DCGEaMk-zJefCVc-LJEbFXR_sbp.jpeg',
        title: 'Healthy bowl with mango, edamame beans, seaweed, rice, spinach, soft egg and nut sauce',
        category: 'salads',
        price: 159,
        id: 7,
        description: '275 g',
    },
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/tgnlnKc-nIJShjI-iulTBwF_kwC.jpeg',
        title: 'Spring salad of young cabbage, radish, soft-boiled egg and paprika-sour cream sauce',
        category: 'salads',
        price: 98,
        id: 8,
        description: '250 g',
    },
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/JByobbG-RCPHQeq-fbxtJyJ_.jpeg',
        title: 'Salad with avocado, sun-dried tomatoes, roasted peppers and fresh herbs',
        category: 'salads',
        price: 179,
        id: 9,
        description: '200 g',
    },
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/DVGzboz-KtODPLb-BGDpGY_xuH.jpeg',
        title: 'Classic Caesar with a soft egg, parmesan and grilled chicken',
        category: 'salads',
        price: 198,
        id: 10,
        description: '250 g',
    },    
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/hIulkiD-YMmIQCG-ngsFGpt_Puy.jpeg',
        title: 'Classic Caesar 2.0 with a soft egg, parmesan and tiger shrimps',
        category: 'salads',
        price: 229,
        id: 11,
        description: '250 g',
    },   
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/ThZvVal-inSbuMD-CFcyVkD_VeZ.jpeg',
        title: 'Warm salad with salmon, tiger prawns, squid and mussels',
        category: 'salads',
        price: 249,
        id: 12,
        description: '265 g',
    }, 
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/KqAbZYe-tGrfxGL-ilduAMs_Jyd.jpeg',
        title: 'Borscht with sour cream is served with rye bread and salo with garlic and herbs',
        category: 'soups',
        price: 108,
        id: 13,
        description: '350 g',
    },    
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/pCoHnbK-JYrkJNc-DvbClqU_jrq.jpeg',
        title: 'Rich chicken broth with homemade noodles and meatballs',
        category: 'soups',
        price: 98,
        id: 14,
        description: '320 g',
    },   
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/HGyGbFT-AzslGw-wMIIAlM_vsU.jpeg',
        title: 'Okroshka with chicken and sausage',
        category: 'soups',
        price: 98,
        id: 15,
        description: '320 g',
    }, 
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/jJkbleb-JioTHQz-nLfiRfb_mHq.jpeg',
        title: 'Spicy Tom yam soup with salmon and tiger shrimps',
        category: 'soups',
        price: 229,
        id: 16,
        description: '350 g',
    },
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/zYleKFT-FLHPDKx-ppuFYjb_uGi.jpeg',
        title: 'Carbonara',
        category: 'pasta, risorro, ravioli',
        price: 198,
        id: 17,
        description: '240 g',
    },
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/XaXZSdV-ryDbfiP-nxXLTGM_GzE.jpeg',
        title: 'Very cheese pasta with truffle oil',
        category: 'pasta, risorro, ravioli',
        price: 198,
        id: 18,
        description: '250 g',
    },
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/vaxGHol-LdbLLg-IgFJkba_GzU.jpeg',
        title: 'Pasta with seafood and tomato sauce',
        category: 'pasta, risorro, ravioli',
        price: 269,
        id: 19,
        description: '350 g',
    },
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/IyMeJff-zNtjCml-wSTZMUe_AyQ.jpeg',
        title: 'Risotto with chicken and king oyster mushrooms, roasted onions and spinach',
        category: 'pasta, risorro, ravioli',
        price: 198,
        id: 20,
        description: '320 g',
    },
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/gMIEfey-uarQGD-nwWJWWB_kiz.jpeg',
        title: 'Burger with veal cutlet, pickled vegetables and french fries',
        category: 'meat and poultry',
        price: 209,
        id: 21,
        description: '400 g',
    },
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/qVxxMYv-FcfIkRi-nWKmuwX_eGl.jpeg',
        title: 'Burger with chicken cutlet, crispy bacon and french fries',
        category: 'meat and poultry',
        price: 209,
        id: 22,
        description: '400 g',
    },
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/tElDFti-cTldVii-wZrNJCH_GMP.jpeg',
        title: 'Duck leg confit with quince, citrus sauce demi glass and viburnum coulis',
        category: 'meat and poultry',
        price: 298,
        id: 23,
        description: '300 g',
    },
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/rZYNFCS-xPbxpei-yUqQBH_Mlh.jpeg',
        title: 'Chicken skewers with almond flakes, hot chili, pickled onions on crispy pita',
        category: 'meat and poultry',
        price: 159,
        id: 24,
        description: '300 g',
    },
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/lYmYXDH-nIGKbA-DbsiBND_iSb.jpeg',
        title: 'Pork neck kebab with pickled onion, greens and red ajika on crunchy pita bread',
        category: 'meat and poultry',
        price: 259,
        id: 25,
        description: '350 g',
    },
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/WlyUGH-RqJEFbm-HGGrYSc_PXl.jpeg',
        title: 'Half a kilo of juicy BBQ pork ribs with homemade adjika',
        category: 'meat and poultry',
        price: 349,
        id: 26,
        description: '600 g',
    },
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/balkjFz-hHpTkxf-svnzMMC_Tnt.jpeg',
        title: 'Pork medallions in crispy smoked bacon with potatoes and creamy truffle sauce',
        category: 'meat and poultry',
        price: 219,
        id: 27,
        description: '300 g',
    },
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/JGzWeQk-GioGLDv-LzwZbnK_Uw.jpeg',
        title: 'Fillet minion on spicy vegetable mousse with grilled tomatoes and broccoli',
        category: 'meat and poultry',
        price: 329,
        id: 28,
        description: '250 g',
    },
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/VMQWKmm-HnMzwiW-clrmnjJ_bKT.jpeg',
        title: 'Creamy mashed potatoes',
        category: 'side dishes',
        price: 79,
        id: 29,
        description: '200 g',
    },
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/AsWKFZr-RYIqvHj-JIfIcbW_TTw.jpeg',
        title: 'Baby potatoes with garlic and greens',
        category: 'side dishes',
        price: 79,
        id: 30,
        description: '150 g',
    },
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/tJjVCqE-lGSHCtu-GHBtIgk_COw.jpeg',
        title: 'Coal-roasted vegetables with green',
        category: 'side dishes',
        price: 129,
        id: 31,
        description: '210 g',
    },
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/CGabIsJ-BITDbJi-kmFUXWF_THL.jpeg',
        title: 'Kyiv cake',
        category: 'desserts',
        price: 119,
        id: 32,
        description: '110 g',
    },
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/rYITMWi-HiSJdJ-SyxVUps_DD.jpeg',
        title: 'Hohey cake',
        category: 'desserts',
        price: 119,
        id: 33,
        description: '110 g',
    },
    {
        image: 'https://prod-choiceqr-media.s3.eu-central-1.amazonaws.com/prod-eat-barsukrest2/menu/SCgGlSr-VcFRxel-IGXIoCD_SkX.jpeg',
        title: 'New York Cheesecake',
        category: 'desserts',
        price: 139,
        id: 34,
        description: '110 g',
    }
]
